--------------------------------------------------------------------------------
-- Skill LastHit
-- Hold-key spell last-hit for lane/neutral creeps.
-- Thin CS engine: live damage (SV + amp + resist) + ability geometry + face-before-cast.
-- No DPS prediction / AoE greed / charge math — secure kill = HP <= dmg - buffer.
-- Abilities MultiSelect always mirrors the local hero (no bind required).
-- Ability on/off prefs persist in Config (SkillLastHit / ability.*).
-- author: by 花曇り hanagumori
--------------------------------------------------------------------------------

local Script = {}

--------------------------------------------------------------------------------
-- STATE
--------------------------------------------------------------------------------

local UI = {}
local menuGroup = nil
local currentHeroName = nil
local currentHeroAbilitySignature = nil
local abilitiesUiReady = false
local abilitiesCallbackBound = false
-- Explicit user on/off per ability id. nil = never set → default ON.
-- Survives reload/game via Config; in-memory cache avoids repeated ReadInt.
local abilitiesPrefs = {}
local CONFIG_SECTION = "SkillLastHit"
local ABILITY_PREF_PREFIX = "ability."

local lastCastTime = 0
local lastCastLockDuration = 0
local CAST_INTERVAL = 0.20

local lastTargetEntity = nil
local lastTargetTime = 0
local lastTargetLockDuration = 0

local AUTO_ATTACK_RANGE_EPSILON = 48
local SAFETY_BUFFER_FLAT = 10
local SAFETY_BUFFER_PER_CASTPOINT = 25
local ABILITY_SLOT_SCAN = 32
local ORDER_ID = "ability_lasthit"
local DEBUG_PREFIX = "[SkillLH] "
local lastDebugTime = 0
local DEBUG_INTERVAL = 1.0
local lastDebugByKey = {}
local resolvedAbilityInfoCache = {}

local CONDITION_ITEMS = {
    smart = "smart",
}
local CREEP_FILTER_ITEMS = {
    melee = "melee",
    ranged = "ranged",
    neutral = "neutral",
    siege = "siege",
}

local Icons = {
    enable     = "\u{f00c}", -- check (Switch ctor = no plate)
    abilities  = "\u{f890}", -- sparkles
    conditions = "\u{f05b}", -- crosshair
    creeps     = "\u{f21b}",
    mana       = "\u{f72e}",
    debug      = "\u{f188}",
}

local MENU_LANG = "ru"
local languageWidget = nil
local I18N = {
    ru = {
        settings = "Настройки",
        enable = "Включить",
        enable_tip = "Автодобив спеллами, пока держишь хоткей Last Hit Helper.",
        conditions = "Условия",
        conditions_tip = "Доп. правила выбора каста.",
        creeps = "Крипы",
        creeps_tip = "Какие типы крипов можно добивать.",
        min_mana = "Мана %",
        min_mana_tip = "Ниже порога скрипт не тратит ману на фарм.",
        debug = "Лог",
        debug_tip = "Писать расчёты и выбранный каст в лог.",
        abilities = "Abilities",
        abilities_tip = "Нюки текущего героя. Список всегда актуален.",
        cond_smart = "Не воровать у тычки",
        creep_melee = "Ближний бой",
        creep_ranged = "Дальний бой",
        creep_neutral = "Нейтралы",
        creep_siege = "Катапульты",
    },
    en = {
        settings = "Settings",
        enable = "Enable",
        enable_tip = "Spell last-hit while the Last Hit Helper hotkey is held.",
        conditions = "Conditions",
        conditions_tip = "Extra cast rules.",
        creeps = "Creeps",
        creeps_tip = "Which creep types can be secured.",
        min_mana = "Mana %",
        min_mana_tip = "Stop spending mana for farm below this threshold.",
        debug = "Log",
        debug_tip = "Write damage checks and chosen casts to the log.",
        abilities = "Abilities",
        abilities_tip = "Current hero nukes. Always kept in sync.",
        cond_smart = "Respect attack",
        creep_melee = "Melee",
        creep_ranged = "Ranged",
        creep_neutral = "Neutrals",
        creep_siege = "Siege",
    },
    cn = {
        settings = "设置",
        enable = "启用",
        enable_tip = "按住 Last Hit Helper 热键时自动用技能补刀。",
        conditions = "条件",
        conditions_tip = "施法额外规则。",
        creeps = "小兵",
        creeps_tip = "允许补刀的小兵类型。",
        min_mana = "法力%",
        min_mana_tip = "低于此法力百分比后不再用技能刷兵。",
        debug = "日志",
        debug_tip = "输出伤害判断与施法结果。",
        abilities = "Abilities",
        abilities_tip = "当前英雄技能列表，始终同步。",
        cond_smart = "不抢普攻",
        creep_melee = "近战",
        creep_ranged = "远程",
        creep_neutral = "野怪",
        creep_siege = "攻城车",
    },
}

--------------------------------------------------------------------------------
-- PROFILES (generated)
--------------------------------------------------------------------------------

-- <<LASTHIT_PROFILES_BEGIN>>
-- Auto-generated by gen_lasthit_profiles.py — do not hand-edit.
-- Regenerate:
-- python .cursor/skills/umbrella-script-authoring/scripts/gen_lasthit_profiles.py
local LASTHIT_PROFILES = {
    ["abaddon_death_coil"] = { beh = "target", dmgKey = "target_damage", castRange = 625, projSpeed = 1300, selfDamageKeys = { "self_damage_enemy_target", "self_damage" }, selfHpBuffer = 40 },
    ["abyssal_underlord_firestorm"] = { beh = "point", dmgKey = "wave_damage", radiusKey = "radius", castRange = 675 },
    ["abyssal_underlord_pit_of_malice"] = { beh = "point", dmgKey = "pit_damage", radiusKey = "radius", castRange = 675 },
    ["alchemist_acid_spray"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 900 },
    ["alchemist_unstable_concoction"] = { beh = "no_target", dmgKey = "max_damage", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 775 },
    ["alchemist_unstable_concoction_throw"] = { beh = "target", dmgKey = "max_damage", radiusKey = "midair_explosion_radius", castRange = 775 },
    ["ancient_apparition_chilling_touch"] = { beh = "target", dmgKey = "damage" },
    ["ancient_apparition_cold_feet"] = { beh = "target", dmgKey = "damage_per_second", castRange = 700 },
    ["ancient_apparition_ice_age"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 800 },
    ["ancient_apparition_ice_vortex"] = { beh = "point", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 1200 },
    ["antimage_counterspell"] = { beh = "no_target", dmgKey = "incoming_damage" },
    ["antimage_mana_overload"] = { beh = "point", dmgKey = "incoming_damage" },
    ["arc_warden_flux"] = { beh = "target", dmgKey = "damage_per_second", radiusKey = "search_radius" },
    ["arc_warden_spark_wraith"] = { beh = "point", dmgKey = "spark_damage_base", radiusKey = "radius", castRange = 2000 },
    ["axe_battle_hunger"] = { beh = "target", dmgKey = "damage_per_second", dmgTypeOverride = "pure", castRange = 700 },
    ["bane_brain_sap"] = { beh = "target", dmgKey = "brain_sap_damage", dmgTypeOverride = "pure" },
    ["bane_enfeeble"] = { beh = "target", dmgKey = "enfeeble_tick_damage", dmgTypeOverride = "pure", castRange = 700 },
    ["batrider_firefly"] = { beh = "no_target", dmgKey = "damage_per_second", radiusKey = "radius" },
    ["batrider_flamebreak"] = { beh = "point", dmgKey = "damage_impact", radiusKey = "explosion_radius", castRange = 1300 },
    ["batrider_sticky_napalm"] = { beh = "point", dmgKey = "damage", radiusKey = "radius" },
    ["beastmaster_summon_raptor"] = { beh = "no_target", dmgKey = "dive_damage", radiusKey = "attack_radius" },
    ["beastmaster_summon_raptor_attack"] = { beh = "target", dmgKey = "burn_damage", radiusKey = "impact_radius", castRange = 1200 },
    ["beastmaster_summon_razorback"] = { beh = "no_target", dmgKey = "boar_base_damage", dmgTypeOverride = "physical" },
    ["beastmaster_wild_axes"] = { beh = "point", dmgKey = "axe_damage", radiusKey = "radius", castRange = 1500 },
    ["black_dragon_fireball"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 1000 },
    ["bloodseeker_blood_bath"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "pure", radiusKey = "radius", castRange = 1500 },
    ["bloodseeker_bloodrage"] = { beh = "no_target", dmgKey = "damage_pct", dmgTypeOverride = "pure" },
    ["bounty_hunter_jinada"] = { beh = "target", dmgKey = "bonus_damage", dmgTypeOverride = "physical", castRange = 150 },
    ["bounty_hunter_shuriken_toss"] = { beh = "target", dmgKey = "bonus_damage", radiusKey = "bounce_aoe", projSpeed = 1000 },
    ["brewmaster_cinder_brew"] = { beh = "point", dmgKey = "total_ignite_damage" },
    ["brewmaster_earth_hurl_boulder"] = { beh = "target", dmgKey = "damage", castRange = 800 },
    ["brewmaster_primal_companion"] = { beh = "no_target", dmgKey = "cooldown_on_take_damage" },
    ["brewmaster_storm_cyclone"] = { beh = "target", dmgKey = "landing_damage", castRange = 600 },
    ["brewmaster_storm_dispel_magic"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 500 },
    ["brewmaster_storm_wind_walk"] = { beh = "no_target", dmgKey = "bonus_damage" },
    ["brewmaster_thunder_clap"] = { beh = "no_target", dmgKey = "damage", radiusKey = "radius" },
    ["bristleback_quill_spray"] = { beh = "no_target", dmgKey = "quill_base_damage", dmgTypeOverride = "physical", radius = 700, radiusKey = "radius", needFace = true },
    ["broodmother_insatiable_hunger"] = { beh = "no_target", dmgKey = "bonus_damage", dmgTypeOverride = "physical", radiusKey = "aura_radius" },
    ["broodmother_silken_bola"] = { beh = "target", dmgKey = "impact_damage", castRange = 750 },
    ["centaur_double_edge"] = { beh = "target", dmgKey = "edge_damage", radiusKey = "radius", castRange = 175 },
    ["centaur_hoof_stomp"] = { beh = "no_target", dmgKey = "stomp_damage", radiusKey = "radius" },
    ["chaos_knight_chaos_bolt"] = { beh = "target", dmgKey = "damage_min", projSpeed = 700 },
    ["chen_holy_persuasion"] = { beh = "target", dmgKey = "damage_bonus", castRange = 600 },
    ["chen_penitence"] = { beh = "target", dmgKey = "damage", dmgTypeOverride = "pure", castRange = 800 },
    ["chen_test_of_faith"] = { beh = "target", dmgKey = "damage_min", dmgTypeOverride = "pure", castRange = 600 },
    ["clinkz_searing_arrows"] = { beh = "target", dmgKey = "damage_bonus", dmgTypeOverride = "physical" },
    ["clinkz_tar_bomb"] = { beh = "target", dmgKey = "impact_damage", dmgTypeOverride = "magical", radius = 325, radiusKey = "radius", castRange = 1000, projSpeed = 2000 },
    ["crystal_maiden_crystal_nova"] = { beh = "point", dmgKey = "nova_damage", radius = 425, radiusKey = "radius" },
    ["crystal_maiden_frostbite"] = { beh = "target", dmgKey = "damage_per_second" },
    ["dark_seer_ion_shell"] = { beh = "target", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 800 },
    ["dark_seer_vacuum"] = { beh = "point", dmgKey = "damage", radius = 400, radiusKey = "radius", castRange = 450 },
    ["dark_troll_warlord_raise_dead"] = { beh = "no_target", dmgKey = "skeletons_damage" },
    ["dark_willow_bramble_maze"] = { beh = "point", dmgKey = "damage_per_tick", castRange = 1000 },
    ["dark_willow_shadow_realm"] = { beh = "no_target", dmgKey = "damage" },
    ["dawnbreaker_celestial_hammer"] = { beh = "point", dmgKey = "burn_damage", radiusKey = "projectile_radius" },
    ["dawnbreaker_fire_wreath"] = { beh = "no_target", dmgKey = "swipe_damage", dmgTypeOverride = "physical", radius = 300, radiusKey = "swipe_radius", needFace = true },
    ["dazzle_poison_touch"] = { beh = "target", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "start_radius", castRange = 500 },
    ["dazzle_rain_of_vermin"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 800 },
    ["death_prophet_carrion_swarm"] = { beh = "point", dmgKey = "damage", radiusKey = "start_radius", castRange = 900, lineProjectile = true, lineRadius = 300 },
    ["death_prophet_spirit_siphon"] = { beh = "target", dmgKey = "damage", castRange = 500 },
    ["disruptor_glimpse"] = { beh = "target", dmgKey = "min_damage", castRange = 600 },
    ["disruptor_thunder_strike"] = { beh = "target", dmgKey = "strike_damage", radiusKey = "radius" },
    ["doom_bringer_infernal_blade"] = { beh = "target", dmgKey = "burn_damage", castRange = 200 },
    ["doom_bringer_scorched_earth"] = { beh = "no_target", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 666 },
    ["dragon_knight_breathe_fire"] = { beh = "point", dmgKey = "damage", radiusKey = "start_radius", lineProjectile = true, lineRadius = 200, projSpeed = 1050 },
    ["dragon_knight_dragon_tail"] = { beh = "target", dmgKey = "damage", radiusKey = "aoe", castRange = 150 },
    ["dragon_knight_fireball"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 600 },
    ["drow_ranger_frost_arrows"] = { beh = "target", dmgKey = "damage", dmgTypeOverride = "physical", castRange = 625 },
    ["drow_ranger_glacier"] = { beh = "no_target", dmgKey = "damage_bonus", radiusKey = "ramp_radius", castRange = 400 },
    ["earth_spirit_boulder_smash"] = { beh = "point", dmgKey = "rock_damage", radiusKey = "radius", castRange = 150 },
    ["earth_spirit_geomagnetic_grip"] = { beh = "point", dmgKey = "rock_damage", radiusKey = "radius", castRange = 1000 },
    ["earth_spirit_petrify"] = { beh = "target", dmgKey = "damage", radiusKey = "aoe", castRange = 175 },
    ["earth_spirit_rolling_boulder"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 3000 },
    ["earth_spirit_stone_caller"] = { beh = "point", dmgKey = "attack_damage_per_stone", castRange = 1100 },
    ["earthshaker_enchant_totem"] = { beh = "no_target", dmgKey = "totem_damage_percentage" },
    ["earthshaker_fissure"] = { beh = "point", dmgKey = "fissure_damage", radiusKey = "fissure_radius", lineProjectile = true, lineRadius = 150 },
    ["elder_titan_ancestral_spirit"] = { beh = "point", dmgKey = "pass_damage", radiusKey = "radius" },
    ["ember_spirit_activate_fire_remnant"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 99999 },
    ["ember_spirit_flame_guard"] = { beh = "no_target", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 400 },
    ["ember_spirit_searing_chains"] = { beh = "no_target", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 400 },
    ["ember_spirit_sleight_of_fist"] = { beh = "point", dmgKey = "bonus_hero_damage", dmgTypeOverride = "physical", radius = 250, radiusKey = "radius", castRange = 650 },
    ["enchantress_enchant"] = { beh = "target", dmgKey = "enchant_damage", castRange = 500 },
    ["enchantress_impetus"] = { beh = "target", dmgKey = "distance_damage_pct", dmgTypeOverride = "pure", castRange = 575 },
    ["enigma_demonic_conversion"] = { beh = "point", dmgKey = "eidelon_base_damage", dmgTypeOverride = "physical", castRange = 400 },
    ["enigma_malefice"] = { beh = "target", dmgKey = "damage", castRange = 450 },
    ["enigma_midnight_pulse"] = { beh = "point", dmgKey = "base_damage", radiusKey = "radius", castRange = 700 },
    ["frogmen_arm_of_the_deep"] = { beh = "point", dmgKey = "damage", castRange = 275 },
    ["frogmen_congregation_of_the_deep"] = { beh = "no_target", dmgKey = "damage" },
    ["frogmen_tendrils_of_the_deep"] = { beh = "point", dmgKey = "damage", castRange = 300 },
    ["furion_curse_of_the_forest"] = { beh = "no_target", dmgKey = "damage_per_tree", radiusKey = "radius" },
    ["furion_force_of_nature"] = { beh = "point", dmgKey = "treant_damage", radiusKey = "area_of_effect", castRange = 750 },
    ["furion_hedgerow"] = { beh = "point", dmgKey = "damage_per_tick" },
    ["furion_sprout"] = { beh = "point", dmgKey = "sprout_damage", radiusKey = "sprout_damage_radius", castRange = 625 },
    ["furion_summon_fey"] = { beh = "target", dmgKey = "attack_damage", radiusKey = "attack_radius", castRange = 600 },
    ["giant_wolf_intimidate"] = { beh = "no_target", dmgKey = "damage_reduction", radiusKey = "radius" },
    ["greevil_blade_fury"] = { beh = "no_target", dmgKey = "customval_damage", radiusKey = "blade_fury_radius" },
    ["greevil_cold_snap"] = { beh = "target", dmgKey = "customval_damage", castRange = 1000 },
    ["greevil_diabolic_edict"] = { beh = "no_target", dmgKey = "customval_damage", dmgTypeOverride = "physical", radiusKey = "radius" },
    ["greevil_hook"] = { beh = "point", dmgKey = "customval_damage", dmgTypeOverride = "pure", radiusKey = "vision_radius", castRange = 700 },
    ["greevil_ice_wall"] = { beh = "no_target", dmgKey = "customval_damage_per_second", radiusKey = "wall_element_radius" },
    ["greevil_leech_seed"] = { beh = "target", dmgKey = "customval_leech_damage", radiusKey = "radius", castRange = 350 },
    ["greevil_magic_missile"] = { beh = "target", dmgKey = "customval_damage", castRange = 500 },
    ["greevil_maledict"] = { beh = "point", dmgKey = "customval_bonus_damage", radiusKey = "radius", castRange = 400 },
    ["greevil_miniboss_blue_cold_feet"] = { beh = "target", dmgKey = "damage", castRange = 700 },
    ["greevil_miniboss_purple_plague_ward"] = { beh = "point", dmgKey = "ward_damage_tooltip", dmgTypeOverride = "physical", castRange = 450 },
    ["greevil_miniboss_purple_venomous_gale"] = { beh = "point", dmgKey = "tick_damage", radiusKey = "radius", castRange = 600 },
    ["greevil_miniboss_yellow_ion_shell"] = { beh = "target", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 600 },
    ["greevil_shadow_strike"] = { beh = "target", dmgKey = "customval_strike_damage", castRange = 400 },
    ["grimstroke_dark_artistry"] = { beh = "point", dmgKey = "damage", radiusKey = "start_radius", lineProjectile = true, lineRadius = 200 },
    ["grimstroke_dark_portrait"] = { beh = "target", dmgKey = "images_do_damage_percent", castRange = 1200 },
    ["grimstroke_ink_creature"] = { beh = "target", dmgKey = "pop_damage", radiusKey = "infection_search_radius", castRange = 900 },
    ["grimstroke_ink_over"] = { beh = "target", dmgKey = "total_damage", castRange = 950 },
    ["gyrocopter_homing_missile"] = { beh = "target", dmgKey = "hit_damage", castRange = 1050 },
    ["gyrocopter_rocket_barrage"] = { beh = "no_target", dmgKey = "rocket_damage", radiusKey = "radius" },
    ["harpy_storm_chain_lightning"] = { beh = "target", dmgKey = "initial_damage", castRange = 900 },
    ["hoodwink_acorn_shot"] = { beh = "point", dmgKey = "acorn_shot_damage", dmgTypeOverride = "physical", castRange = 675, projSpeed = 2200, attackPctKey = "base_damage_pct", noSpellAmp = true },
    ["hoodwink_bushwhack"] = { beh = "point", dmgKey = "total_damage", radiusKey = "trap_radius", castRange = 1100 },
    ["huskar_burning_spear"] = { beh = "target", dmgKey = "burn_damage", castRange = 450 },
    ["huskar_inner_fire"] = { beh = "no_target", dmgKey = "damage", radiusKey = "radius", castRange = 500 },
    ["ice_shaman_incendiary_bomb"] = { beh = "target", dmgKey = "burn_damage", castRange = 700 },
    ["invoker_chaos_meteor"] = { beh = "target", dmgKey = "main_damage", radius = 275, delayedAoE = true },
    ["invoker_chaos_meteor_ad"] = { beh = "point", dmgKey = "main_damage", radiusKey = "area_of_effect", castRange = 700 },
    ["invoker_cold_snap"] = { beh = "target", dmgKey = "damage" },
    ["invoker_cold_snap_ad"] = { beh = "target", dmgKey = "freeze_damage", castRange = 1000 },
    ["invoker_deafening_blast"] = { beh = "target", dmgKey = "damage", radius = 175, lineProjectile = true, lineRadius = 175 },
    ["invoker_deafening_blast_ad"] = { beh = "point", dmgKey = "damage", radiusKey = "radius_start", castRange = 1000 },
    ["invoker_emp_ad"] = { beh = "point", dmgKey = "damage_per_mana_pct", radiusKey = "area_of_effect", castRange = 950 },
    ["invoker_exort"] = { beh = "no_target", dmgKey = "bonus_damage_per_instance" },
    ["invoker_forge_spirit_ad"] = { beh = "no_target", dmgKey = "spirit_damage" },
    ["invoker_ice_wall_ad"] = { beh = "no_target", dmgKey = "damage_per_second" },
    ["invoker_sun_strike"] = { beh = "target", dmgKey = "damage", dmgTypeOverride = "pure", radius = 175, delayedAoE = true },
    ["invoker_sun_strike_ad"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "pure", radiusKey = "area_of_effect" },
    ["invoker_tornado"] = { beh = "target", dmgKey = "base_damage", radius = 200, lineProjectile = true, lineRadius = 200 },
    ["invoker_tornado_ad"] = { beh = "point", dmgKey = "base_damage", radiusKey = "area_of_effect", castRange = 2000 },
    ["jakiro_dual_breath"] = { beh = "point", dmgKey = "burn_damage", radiusKey = "start_radius", lineProjectile = true, lineRadius = 250 },
    ["jakiro_ice_path"] = { beh = "point", dmgKey = "damage", radiusKey = "path_radius", castRange = 1100 },
    ["jakiro_liquid_fire"] = { beh = "target", dmgKey = "damage", radiusKey = "radius", castRange = 600 },
    ["jakiro_liquid_ice"] = { beh = "target", dmgKey = "damage", castRange = 600 },
    ["juggernaut_blade_fury"] = { beh = "no_target", dmgKey = "blade_fury_damage", radiusKey = "blade_fury_radius" },
    ["juggernaut_trinity"] = { beh = "no_target", dmgKey = "damage_pct", dmgTypeOverride = "physical", radiusKey = "jump_attack_radius", castRange = 475 },
    ["keeper_of_the_light_blinding_light"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 500 },
    ["keeper_of_the_light_will_o_wisp"] = { beh = "point", dmgKey = "wisp_damage", radiusKey = "radius", castRange = 800 },
    ["kez_echo_slash"] = { beh = "no_target", dmgKey = "katana_echo_damage", dmgTypeOverride = "physical", radiusKey = "katana_radius", slashLength = 800, slashLengthKey = "katana_distance", needFace = true, lineRadius = 200, noSpellAmp = true },
    ["kez_falcon_rush"] = { beh = "no_target", dmgKey = "base_echo_damage" },
    ["kez_kazurai_katana"] = { beh = "target", dmgKey = "katana_bleed_attack_damage_pct", dmgTypeOverride = "physical", castRange = 200 },
    ["kez_switch_weapons"] = { beh = "no_target", dmgKey = "katana_swap_bonus_damage" },
    ["kez_talon_toss"] = { beh = "target", dmgKey = "damage", dmgTypeOverride = "physical", castRange = 650 },
    ["kunkka_tidal_wave"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 1050 },
    ["kunkka_tidebringer"] = { beh = "target", dmgKey = "cleave_damage", dmgTypeOverride = "physical", castRange = 150 },
    ["kunkka_torrent"] = { beh = "point", dmgKey = "torrent_damage", radius = 250, radiusKey = "radius", castRange = 1300, delayedAoE = true, impactDelayKey = "delay" },
    ["largo_catchy_lick"] = { beh = "target", dmgKey = "damage" },
    ["largo_frogstomp"] = { beh = "point", dmgKey = "damage_per_stomp", radiusKey = "radius" },
    ["legion_commander_overwhelming_odds"] = { beh = "no_target", dmgKey = "damage", radius = 330, radiusKey = "radius" },
    ["leshrac_diabolic_edict"] = { beh = "no_target", dmgKey = "damage", dmgTypeOverride = "pure", radiusKey = "radius" },
    ["leshrac_lightning_storm"] = { beh = "target", dmgKey = "damage", radiusKey = "radius", castRange = 600 },
    ["leshrac_split_earth"] = { beh = "point", radiusKey = "radius", castRange = 650, delayedAoE = true, impactDelayKey = "delay" },
    ["lich_frost_nova"] = { beh = "target", dmgKey = "blast_damage", radiusKey = "radius", castRange = 575 },
    ["lina_dragon_slave"] = { beh = "point", dmgKey = "dragon_slave_damage", castRange = 1075, lineProjectile = true, lineRadius = 275 },
    ["lina_light_strike_array"] = { beh = "point", dmgKey = "light_strike_array_damage", radiusKey = "light_strike_array_aoe", castRange = 700, delayedAoE = true, impactDelayKey = "light_strike_array_delay_time" },
    ["lion_impale"] = { beh = "point", dmgKey = "damage", radiusKey = "width", lineProjectile = true, lineRadius = 150 },
    ["lone_druid_entangle"] = { beh = "point", dmgKey = "damage", radiusKey = "active_radius", castRange = 700 },
    ["lone_druid_spirit_bear"] = { beh = "no_target", dmgKey = "backlash_damage" },
    ["lone_druid_spirit_bear_fetch"] = { beh = "target", dmgKey = "damage", castRange = 200 },
    ["luna_lucent_beam"] = { beh = "target", dmgKey = "beam_damage", castRange = 800 },
    ["luna_lunar_orbit"] = { beh = "no_target", dmgKey = "rotating_glaives_collision_damage", dmgTypeOverride = "physical", radiusKey = "rotating_glaives_movement_radius" },
    ["lycan_howl"] = { beh = "no_target", dmgKey = "attack_damage_reduction", radiusKey = "radius" },
    ["lycan_summon_wolves"] = { beh = "no_target", dmgKey = "wolf_damage" },
    ["lycan_summon_wolves_hamstring"] = { beh = "target", dmgKey = "damage_boost", dmgTypeOverride = "physical", castRange = 150 },
    ["magnataur_horn_toss"] = { beh = "no_target", dmgKey = "damage", radiusKey = "radius" },
    ["magnataur_shockwave"] = { beh = "point", dmgKey = "shock_damage", lineProjectile = true, lineRadius = 200, projSpeed = 1200 },
    ["magnataur_skewer"] = { beh = "point", dmgKey = "skewer_damage", radiusKey = "skewer_radius" },
    ["marci_grapple"] = { beh = "target", dmgKey = "impact_damage", radiusKey = "landing_radius", castRange = 175 },
    ["mars_bulwark"] = { beh = "point", dmgKey = "physical_damage_reduction" },
    ["mars_gods_rebuke"] = { beh = "no_target", dmgKey = "bonus_damage_vs_heroes", dmgTypeOverride = "physical", radius = 500, radiusKey = "radius", needFace = true, critPctKey = "crit_mult", noSpellAmp = true },
    ["mars_spear"] = { beh = "point", dmgKey = "damage", lineProjectile = true, lineRadius = 125, projSpeed = 1400 },
    ["medusa_gorgon_grasp"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 625 },
    ["medusa_mystic_snake"] = { beh = "target", dmgKey = "snake_damage", radiusKey = "radius" },
    ["meepo_megameepo"] = { beh = "no_target", dmgKey = "poof_damage_factor", radiusKey = "radius" },
    ["meepo_poof"] = { beh = "point", dmgKey = "poof_damage", radiusKey = "radius" },
    ["mirana_arrow"] = { beh = "point", dmgKey = "arrow_bonus_damage", castRange = 3000 },
    ["mirana_starfall"] = { beh = "no_target", dmgKey = "damage", radius = 650, radiusKey = "starfall_radius", needFace = true },
    ["monkey_king_boundless_strike"] = { beh = "point", dmgTypeOverride = "physical", radiusKey = "strike_radius", lineProjectile = true, lineRadius = 150, lineLength = 1100, critPctKey = "strike_crit_mult", flatDamageKey = "strike_flat_damage", noSpellAmp = true },
    ["monkey_king_tree_dance"] = { beh = "target", dmgKey = "jump_damage_cooldown", castRange = 900 },
    ["morphling_adaptive_strike_agi"] = { beh = "target", dmgKey = "damage_min", dmgTypeOverride = "physical", castRange = 600, projSpeed = 1150 },
    ["mud_golem_hurl_boulder"] = { beh = "target", dmgKey = "damage", castRange = 800 },
    ["muerta_spectral_slug"] = { beh = "target", dmgKey = "damage", castRange = 500 },
    ["muerta_the_calling"] = { beh = "point", dmgKey = "damage", radiusKey = "hit_radius", castRange = 600 },
    ["naga_siren_deluge"] = { beh = "no_target", dmgKey = "damage", radiusKey = "radius" },
    ["naga_siren_mirror_image"] = { beh = "no_target", dmgKey = "incoming_damage" },
    ["necrolyte_death_pulse"] = { beh = "no_target", radius = 500, radiusKey = "area_of_effect", needFace = true },
    ["necronomicon_archer_mana_burn"] = { beh = "target", dmgKey = "burn_as_damage_tooltip", castRange = 600 },
    ["nevermore_shadowraze1"] = { beh = "no_target", dmgKey = "shadowraze_damage", radiusKey = "shadowraze_radius", fixedRangeKey = "shadowraze_range", needFace = true },
    ["nevermore_shadowraze2"] = { beh = "no_target", dmgKey = "shadowraze_damage", radiusKey = "shadowraze_radius", fixedRangeKey = "shadowraze_range", needFace = true },
    ["nevermore_shadowraze3"] = { beh = "no_target", dmgKey = "shadowraze_damage", radiusKey = "shadowraze_radius", fixedRangeKey = "shadowraze_range", needFace = true },
    ["night_stalker_void"] = { beh = "target", dmgKey = "damage", castRange = 525 },
    ["nyx_assassin_burrow"] = { beh = "no_target", dmgKey = "damage_reduction", radiusKey = "carapace_radius" },
    ["nyx_assassin_impale"] = { beh = "point", dmgKey = "impale_damage", radiusKey = "width", castRange = 750, lineProjectile = true, lineRadius = 200 },
    ["nyx_assassin_jolt"] = { beh = "target", dmgKey = "damage_echo_pct", castRange = 800 },
    ["nyx_assassin_spiked_carapace"] = { beh = "no_target", dmgKey = "damage_reflect_pct" },
    ["obsidian_destroyer_arcane_orb"] = { beh = "target", dmgKey = "mana_pool_damage_pct", dmgTypeOverride = "pure", castRange = 450 },
    ["obsidian_destroyer_astral_imprisonment"] = { beh = "target", dmgKey = "damage" },
    ["ogre_bruiser_ogre_smash"] = { beh = "point", dmgKey = "damage", radiusKey = "radius" },
    ["ogre_magi_fireblast"] = { beh = "target", dmgKey = "fireblast_damage", castRange = 525 },
    ["ogre_magi_ignite"] = { beh = "target", dmgKey = "burn_damage", radiusKey = "ignite_multicast_aoe", castRange = 700 },
    ["ogre_magi_unrefined_fireblast"] = { beh = "target", dmgKey = "base_damage", castRange = 525 },
    ["omniknight_hammer_of_purity"] = { beh = "target", dmgKey = "base_damage", dmgTypeOverride = "pure", castRange = 150 },
    ["oracle_fates_edict"] = { beh = "target", dmgKey = "magic_damage_resistance_pct_tooltip", castRange = 700 },
    ["oracle_purifying_flames"] = { beh = "target", dmgKey = "damage", castRange = 850 },
    ["oracle_rain_of_destiny"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 650 },
    ["pangolier_shield_crash"] = { beh = "no_target", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "radius" },
    ["pangolier_swashbuckle"] = { beh = "target", dmgTypeOverride = "physical", radius = 200 },
    ["phantom_assassin_fan_of_knives"] = { beh = "no_target", dmgKey = "pct_health_damage", dmgTypeOverride = "physical", radiusKey = "radius" },
    ["phantom_assassin_stifling_dagger"] = { beh = "target", dmgTypeOverride = "physical", castRange = 700, projSpeed = 1200, attackPctKey = "attack_factor_tooltip", flatDamageKey = "base_damage", noSpellAmp = true },
    ["phantom_lancer_spirit_lance"] = { beh = "target", dmgKey = "lance_damage", castRange = 600 },
    ["phoenix_fire_spirits"] = { beh = "no_target", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 1400 },
    ["phoenix_icarus_dive"] = { beh = "point", dmgKey = "damage_per_second", radiusKey = "hit_radius" },
    ["phoenix_launch_fire_spirit"] = { beh = "point", dmgKey = "damage_per_second", radiusKey = "radius", castRange = 1400 },
    ["phoenix_sun_ray"] = { beh = "point", dmgKey = "base_damage", radiusKey = "radius", castRange = 1200 },
    ["primal_beast_onslaught"] = { beh = "point", dmgKey = "knockback_damage", dmgTypeOverride = "physical", radiusKey = "knockback_radius" },
    ["primal_beast_rock_throw"] = { beh = "point", dmgKey = "base_damage", dmgTypeOverride = "physical", radiusKey = "impact_radius", castRange = 1800 },
    ["primal_beast_trample"] = { beh = "no_target", dmgKey = "base_damage", radiusKey = "effect_radius" },
    ["primal_beast_uproar"] = { beh = "no_target", dmgKey = "damage_min", radiusKey = "radius" },
    ["puck_illusory_orb"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 1950, lineProjectile = true, lineRadius = 225, projSpeed = 550 },
    ["puck_waning_rift"] = { beh = "point", dmgKey = "damage", radius = 400, radiusKey = "radius" },
    ["pudge_flesh_heap"] = { beh = "no_target", dmgKey = "damage_block" },
    ["pudge_meat_hook"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "pure", radiusKey = "vision_radius" },
    ["pugna_nether_blast"] = { beh = "point", dmgKey = "blast_damage", radius = 400, radiusKey = "radius", castRange = 600, delayedAoE = true, impactDelayKey = "delay" },
    ["pugna_nether_ward"] = { beh = "point", dmgKey = "base_damage", radiusKey = "radius" },
    ["queenofpain_scream_of_pain"] = { beh = "no_target", dmgKey = "damage", radius = 550, radiusKey = "area_of_effect", needFace = true },
    ["queenofpain_shadow_strike"] = { beh = "target", dmgKey = "strike_damage", castRange = 450 },
    ["rattletrap_battery_assault"] = { beh = "no_target", dmgKey = "damage", radiusKey = "radius" },
    ["rattletrap_overclocking"] = { beh = "no_target", dmgKey = "rocket_flare_damage_pct", radiusKey = "battery_assault_radius" },
    ["rattletrap_power_cogs"] = { beh = "no_target", dmgKey = "damage", radiusKey = "cogs_radius" },
    ["rattletrap_rocket_flare"] = { beh = "point", dmgKey = "damage", radius = 600, radiusKey = "radius", projSpeed = 2250 },
    ["razor_plasma_field"] = { beh = "no_target", dmgKey = "damage_min", radius = 700, radiusKey = "radius", needFace = true },
    ["riki_blink_strike"] = { beh = "target", dmgKey = "bonus_damage", dmgTypeOverride = "physical" },
    ["riki_poison_dart"] = { beh = "target", dmgKey = "damage", castRange = 600 },
    ["ringmaster_impalement"] = { beh = "point", dmgKey = "damage_impact", castRange = 2400 },
    ["rubick_fade_bolt"] = { beh = "target", dmgKey = "damage", radiusKey = "radius", castRange = 800 },
    ["rubick_null_field"] = { beh = "no_target", dmgKey = "magic_damage_reduction_pct", radiusKey = "radius" },
    ["sand_king_burrowstrike"] = { beh = "target", lineProjectile = true, lineRadius = 150 },
    ["sandking_sand_storm"] = { beh = "no_target", dmgKey = "sand_storm_damage", radiusKey = "sand_storm_radius" },
    ["sandking_scorpion_strike"] = { beh = "point", dmgKey = "attack_damage", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 200 },
    ["satyr_trickster_purge"] = { beh = "target", dmgKey = "summon_damage", castRange = 350 },
    ["shadow_demon_disseminate"] = { beh = "target", dmgKey = "damage_reflection_pct", radiusKey = "radius", castRange = 700 },
    ["shadow_demon_shadow_poison"] = { beh = "point", dmgKey = "hit_damage", radiusKey = "radius", castRange = 1500, lineProjectile = true, lineRadius = 200, projSpeed = 1500 },
    ["shadow_shaman_ether_shock"] = { beh = "target", dmgKey = "damage", radiusKey = "start_radius", castRange = 600 },
    ["shadow_shaman_urnaconda"] = { beh = "point", dmgKey = "impact_damage", radiusKey = "impact_radius", castRange = 650 },
    ["shredder_chakram_2"] = { beh = "point", dmgKey = "pass_damage", dmgTypeOverride = "pure", radiusKey = "radius", castRange = 1200 },
    ["shredder_flamethrower"] = { beh = "no_target", dmgKey = "damage_per_second", radiusKey = "width" },
    ["shredder_timber_chain"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "pure", radiusKey = "radius" },
    ["shredder_twisted_chakram"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "pure", radiusKey = "radius", castRange = 1200 },
    ["shredder_whirling_death"] = { beh = "no_target", dmgKey = "whirling_damage", dmgTypeOverride = "pure", radiusKey = "whirling_radius" },
    ["silencer_curse_of_the_silent"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 850 },
    ["silencer_glaives_of_wisdom"] = { beh = "target", dmgKey = "intellect_damage_pct", castRange = 600 },
    ["silencer_last_word"] = { beh = "target", dmgKey = "damage", castRange = 900 },
    ["skeleton_king_bone_guard"] = { beh = "no_target", dmgKey = "talent_skeleton_damage", dmgTypeOverride = "physical" },
    ["skeleton_king_hellfire_blast"] = { beh = "target", dmgKey = "damage", castRange = 525 },
    ["skywrath_mage_arcane_bolt"] = { beh = "target", dmgKey = "bolt_damage", radiusKey = "extra_bolt_search_radius", projSpeed = 500 },
    ["skywrath_mage_concussive_shot"] = { beh = "no_target", dmgKey = "damage", radiusKey = "launch_radius", castRange = 1600 },
    ["slardar_slithereen_crush"] = { beh = "no_target", dmgKey = "crush_damage", dmgTypeOverride = "physical", radius = 350, radiusKey = "crush_radius", needFace = true },
    ["slark_dark_pact"] = { beh = "no_target", dmgKey = "total_damage", radiusKey = "radius" },
    ["snapfire_lil_shredder"] = { beh = "no_target", dmgKey = "damage", dmgTypeOverride = "physical", castRange = 800 },
    ["snapfire_scatterblast"] = { beh = "point", dmgKey = "damage", lineProjectile = true, lineRadius = 225 },
    ["snapfire_spit_creep"] = { beh = "point", dmgKey = "burn_damage", radiusKey = "impact_radius", castRange = 3000 },
    ["sniper_concussive_grenade"] = { beh = "point", dmgKey = "damage", radiusKey = "radius" },
    ["sniper_shrapnel"] = { beh = "point", dmgKey = "shrapnel_damage", radiusKey = "radius", castRange = 1800 },
    ["spawnlord_master_freeze"] = { beh = "target", dmgKey = "damage", dmgTypeOverride = "physical", castRange = 150 },
    ["spawnlord_master_stomp"] = { beh = "no_target", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "radius" },
    ["spectre_spectral_dagger"] = { beh = "point", dmgKey = "damage", radiusKey = "dagger_radius", castRange = 1800 },
    ["storm_spirit_static_remnant"] = { beh = "no_target", dmgKey = "static_remnant_damage", radiusKey = "static_remnant_radius" },
    ["sven_storm_bolt"] = { beh = "target", dmgKey = "scepter_bonus_damage", radius = 250, radiusKey = "bolt_aoe", projSpeed = 1000 },
    ["techies_snare_trap"] = { beh = "point", dmgKey = "damage", radiusKey = "activation_radius", castRange = 150 },
    ["techies_sticky_bomb"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 1000 },
    ["techies_suicide"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 1000 },
    ["templar_assassin_meld"] = { beh = "no_target", dmgKey = "bonus_damage", dmgTypeOverride = "physical" },
    ["templar_assassin_refraction"] = { beh = "no_target", dmgKey = "bonus_damage", dmgTypeOverride = "physical" },
    ["terrorblade_metamorphosis"] = { beh = "no_target", dmgKey = "bonus_damage", dmgTypeOverride = "physical" },
    ["terrorblade_terror_wave"] = { beh = "no_target", dmgKey = "damage", radiusKey = "scepter_radius" },
    ["tidehunter_anchor_smash"] = { beh = "no_target", dmgKey = "attack_damage", dmgTypeOverride = "physical", radius = 375, needFace = true },
    ["tidehunter_arm_of_the_deep"] = { beh = "point", dmgKey = "damage_pct" },
    ["tidehunter_gush"] = { beh = "target", dmgKey = "gush_damage", castRange = 700 },
    ["tidehunter_kraken_shell"] = { beh = "no_target", dmgKey = "damage_cleanse" },
    ["tinker_deploy_turrets"] = { beh = "point", dmgKey = "drop_damage", radiusKey = "drop_aoe_radius", castRange = 600 },
    ["tinker_laser"] = { beh = "target", dmgKey = "laser_damage", dmgTypeOverride = "pure", castRange = 600 },
    ["tinker_march_of_the_machines"] = { beh = "point", dmgKey = "damage", radiusKey = "radius", castRange = 300 },
    ["tinker_warp_grenade"] = { beh = "target", dmgKey = "damage", castRange = 700 },
    ["tiny_avalanche"] = { beh = "point", dmgKey = "avalanche_damage", radiusKey = "radius" },
    ["tiny_toss"] = { beh = "target", dmgKey = "toss_damage", radiusKey = "radius", castRange = 800 },
    ["tiny_toss_tree"] = { beh = "point", dmgKey = "bonus_damage", dmgTypeOverride = "physical", radiusKey = "splash_radius", castRange = 1200 },
    ["tiny_tree_grab"] = { beh = "target", dmgKey = "bonus_damage", dmgTypeOverride = "physical", castRange = 200 },
    ["treant_leech_seed"] = { beh = "target", dmgKey = "leech_damage", radiusKey = "radius", castRange = 150 },
    ["treant_living_armor"] = { beh = "point", dmgKey = "damage_block_base" },
    ["treant_natures_grasp"] = { beh = "point", dmgKey = "damage_per_second", castRange = 1500 },
    ["troll_warlord_whirling_axes_melee"] = { beh = "no_target", dmgKey = "damage", radiusKey = "hit_radius" },
    ["troll_warlord_whirling_axes_ranged"] = { beh = "point", dmgKey = "axe_damage", castRange = 950 },
    ["tusk_ice_shards"] = { beh = "point", dmgKey = "shard_damage", castRange = 1400, lineProjectile = true, lineRadius = 200, projSpeed = 1200 },
    ["tusk_snowball"] = { beh = "target", dmgKey = "snowball_damage", radiusKey = "snowball_windup_radius", castRange = 1150 },
    ["tusk_tag_team"] = { beh = "no_target", dmgKey = "bonus_damage", dmgTypeOverride = "physical", radiusKey = "radius" },
    ["undying_decay"] = { beh = "point", dmgKey = "decay_damage", radius = 325, radiusKey = "radius", castRange = 650 },
    ["undying_soul_rip"] = { beh = "target", dmgKey = "damage_per_unit", radiusKey = "radius", castRange = 750 },
    ["undying_tombstone"] = { beh = "point", dmgKey = "zombie_damage_tooltip", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 500 },
    ["ursa_earthshock"] = { beh = "no_target", radius = 385, radiusKey = "shock_radius", needFace = true },
    ["vengefulspirit_magic_missile"] = { beh = "target", dmgKey = "magic_missile_damage" },
    ["vengefulspirit_wave_of_terror"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "magical", radiusKey = "vision_aoe", castRange = 1400, lineProjectile = true, lineRadius = 325, projSpeed = 2000 },
    ["venomancer_latent_poison"] = { beh = "target", dmgKey = "duration_damage", castRange = 800 },
    ["venomancer_plague_ward"] = { beh = "point", dmgKey = "ward_damage_tooltip", dmgTypeOverride = "physical", castRange = 850 },
    ["venomancer_snakebite"] = { beh = "target", dmgKey = "base_damage", castRange = 600 },
    ["venomancer_venomous_gale"] = { beh = "point", dmgKey = "tick_damage", radiusKey = "radius", lineProjectile = true, lineRadius = 125 },
    ["viper_nethertoxin"] = { beh = "point", dmgKey = "min_damage", radiusKey = "radius", castRange = 900 },
    ["viper_poison_attack"] = { beh = "target", dmgKey = "damage", castRange = 600 },
    ["visage_silent_as_the_grave"] = { beh = "no_target", dmgKey = "bonus_damage" },
    ["visage_soul_assumption"] = { beh = "target", dmgKey = "soul_base_damage", radiusKey = "radius", castRange = 1000, projSpeed = 1000 },
    ["visage_stone_form_self_cast"] = { beh = "no_target", dmgKey = "stun_damage", radiusKey = "stun_radius" },
    ["visage_summon_familiars_stone_form"] = { beh = "no_target", dmgKey = "stun_damage", radiusKey = "stun_radius", castRange = 50 },
    ["void_spirit_aether_remnant"] = { beh = "target", radius = 300 },
    ["void_spirit_dissimilate"] = { beh = "no_target", dmgKey = "damage_radius", radiusKey = "destination_fx_radius" },
    ["void_spirit_resonant_pulse"] = { beh = "no_target", dmgKey = "damage", radius = 500, radiusKey = "radius", needFace = true },
    ["warlock_fatal_bonds"] = { beh = "target", dmgKey = "damage_share_percentage", radiusKey = "search_aoe", castRange = 1000 },
    ["warlock_shadow_word"] = { beh = "target", dmgKey = "damage", radiusKey = "spell_aoe", castRange = 650 },
    ["warpine_raider_seed_shot"] = { beh = "target", dmgKey = "damage", castRange = 575 },
    ["weaver_geminate_attack"] = { beh = "target", dmgKey = "bonus_damage", dmgTypeOverride = "physical", castRange = 425 },
    ["weaver_shukuchi"] = { beh = "no_target", dmgKey = "damage", radiusKey = "radius" },
    ["weaver_the_swarm"] = { beh = "point", dmgKey = "damage", dmgTypeOverride = "physical", radiusKey = "radius", castRange = 3000 },
    ["windrunner_powershot"] = { beh = "target", lineProjectile = true, lineRadius = 125 },
    ["winter_wyvern_arctic_burn"] = { beh = "no_target", dmgKey = "percent_damage", radiusKey = "tree_destruction_radius" },
    ["winter_wyvern_splinter_blast"] = { beh = "target", dmgKey = "damage", radius = 500, radiusKey = "split_radius", castRange = 1150, projSpeed = 1200, excludePrimaryTarget = true, allowAoEOnly = true },
    ["wisp_spirits"] = { beh = "no_target", dmgKey = "hero_damage", radiusKey = "hero_hit_radius" },
    ["witch_doctor_maledict"] = { beh = "point", dmgKey = "bonus_damage", radiusKey = "radius", castRange = 600 },
    ["witch_doctor_paralyzing_cask"] = { beh = "target", dmgKey = "base_damage", castRange = 600 },
    ["zuus_arc_lightning"] = { beh = "target", dmgKey = "arc_damage", radiusKey = "radius", castRange = 800, projSpeed = 1100 },
    ["zuus_heavenly_jump"] = { beh = "no_target", dmgKey = "damage", radiusKey = "vision_radius" },
    ["zuus_lightning_bolt"] = { beh = "point", dmgKey = "damage", radiusKey = "true_sight_radius", castRange = 700 },
}
-- <<LASTHIT_PROFILES_END>>


--------------------------------------------------------------------------------
-- SMALL HELPERS
--------------------------------------------------------------------------------

local function TryCall(fn, ...)
    if type(fn) ~= "function" then
        return false
    end
    return pcall(fn, ...)
end

local function dbg(msg)
    if UI.Debug and UI.Debug:Get() then
        Log.Write(DEBUG_PREFIX .. tostring(msg))
    end
end

local function dbgThrottle(msg)
    if not (UI.Debug and UI.Debug:Get()) then return end
    local now = GameRules.GetGameTime()
    if now - lastDebugTime < DEBUG_INTERVAL then return end
    lastDebugTime = now
    Log.Write(DEBUG_PREFIX .. tostring(msg))
end

local function dbgThrottleKey(key, msg, interval)
    if not (UI.Debug and UI.Debug:Get()) then return end
    local now = GameRules.GetGameTime()
    local cooldown = interval or DEBUG_INTERVAL
    if key and lastDebugByKey[key] and (now - lastDebugByKey[key]) < cooldown then
        return
    end
    if key then
        lastDebugByKey[key] = now
    end
    Log.Write(DEBUG_PREFIX .. tostring(msg))
end

local function t(key)
    local langTable = I18N[MENU_LANG] or I18N.ru or I18N.en or {}
    return langTable[key] or (I18N.en and I18N.en[key]) or tostring(key)
end

local function conditionLabel(itemKey)
    return t("cond_" .. tostring(itemKey))
end

local function creepFilterLabel(itemKey)
    return t("creep_" .. tostring(itemKey))
end

local function detectMenuLanguage()
    if not languageWidget then
        local ok, widget = TryCall(Menu.Find, "SettingsHidden", "", "", "", "Main", "Language")
        if ok and widget then
            languageWidget = widget
        end
    end
    if not languageWidget then
        return MENU_LANG
    end
    local ok, value = TryCall(function() return languageWidget:Get() end)
    if not ok or value == nil then
        return MENU_LANG
    end
    if value == 1 then return "ru" end
    if value == 2 then return "cn" end
    return "en"
end

local function BitAnd(a, b)
    a = math.floor(tonumber(a) or 0)
    b = math.floor(tonumber(b) or 0)
    local out = 0
    local bitValue = 1
    while a > 0 and b > 0 do
        if (a % 2) == 1 and (b % 2) == 1 then
            out = out + bitValue
        end
        a = math.floor(a / 2)
        b = math.floor(b / 2)
        bitValue = bitValue * 2
    end
    return out
end

local function HasBehavior(ability, flag)
    if not ability or not flag then
        return false
    end
    local ok, mask = TryCall(Ability.GetBehavior, ability, false)
    if not ok or not mask then
        return false
    end
    return BitAnd(mask, flag) ~= 0
end

local function SV(ability, key)
    if not ability or not key then
        return nil
    end
    local level = 1
    local okLvl, lvl = TryCall(Ability.GetLevel, ability)
    if okLvl and type(lvl) == "number" and lvl > 0 then
        level = lvl
    end
    local ok, value = TryCall(Ability.GetLevelSpecialValueFor, ability, key, level)
    if ok and type(value) == "number" then
        return value
    end
    return nil
end

local function SVAny(ability, keys)
    for i = 1, #keys do
        local value = SV(ability, keys[i])
        if value and value > 0 then
            return value, keys[i]
        end
    end
    return 0, nil
end

local function cloneInfo(source)
    if type(source) ~= "table" then
        return {}
    end
    local copy = {}
    for key, value in pairs(source) do
        if type(value) == "table" then
            local nested = {}
            for nestedKey, nestedValue in pairs(value) do
                nested[nestedKey] = nestedValue
            end
            copy[key] = nested
        else
            copy[key] = value
        end
    end
    return copy
end

local function mergeInfo(base, extra)
    local merged = cloneInfo(base)
    if type(extra) ~= "table" then
        return merged
    end
    for key, value in pairs(extra) do
        if type(value) == "table" then
            local nested = {}
            for nestedKey, nestedValue in pairs(value) do
                nested[nestedKey] = nestedValue
            end
            merged[key] = nested
        else
            merged[key] = value
        end
    end
    return merged
end

--------------------------------------------------------------------------------
-- ABILITY ACCESS
--------------------------------------------------------------------------------

local function getAbilityName(ability)
    if not ability then
        return nil
    end
    local ok, name = TryCall(Ability.GetName, ability)
    if ok and type(name) == "string" and name ~= "" then
        return name
    end
    return nil
end

local function getAbilityByName(hero, abilityName)
    if not hero or not abilityName then
        return nil
    end
    local ok, ability = TryCall(NPC.GetAbility, hero, abilityName)
    if ok and ability then
        return ability
    end
    return nil
end

local function enumerateHeroAbilities(hero)
    local list = {}
    local seen = {}
    for index = 0, ABILITY_SLOT_SCAN - 1 do
        local ok, ability = TryCall(NPC.GetAbilityByIndex, hero, index)
        if ok and ability then
            local name = getAbilityName(ability)
            local identity = name or tostring(ability)
            if not seen[identity] then
                seen[identity] = true
                list[#list + 1] = ability
            end
        end
    end
    return list
end

local function buildHeroAbilitySignature(hero)
    local heroName = NPC.GetUnitName(hero) or "?"
    local parts = { heroName }
    for _, ability in ipairs(enumerateHeroAbilities(hero)) do
        local name = getAbilityName(ability)
        if name then
            local level = 0
            local ok, value = TryCall(Ability.GetLevel, ability)
            if ok and type(value) == "number" then
                level = value
            end
            parts[#parts + 1] = name .. ":" .. tostring(level)
        end
    end
    return table.concat(parts, "|")
end

local function isAbilityExcluded(ability, allowHidden)
    if not ability then
        return true
    end
    if Ability.IsPassive(ability) or Ability.IsUltimate(ability) then
        return true
    end
    if HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_TOGGLE)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_AUTOCAST)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_ATTACK)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_DIRECTIONAL) then
        return true
    end
    if not allowHidden and Ability.IsHidden(ability) then
        return true
    end
    return false
end

local function resolveBehaviorKind(ability, profile)
    if profile and profile.beh then
        return profile.beh
    end
    if HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET) then
        return "target"
    end
    if HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_OPTIONAL_POINT)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_AOE) then
        return "point"
    end
    if HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET)
        or HasBehavior(ability, Enum.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_OPTIONAL_NO_TARGET) then
        return "no_target"
    end
    return nil
end

local function getFixedRange(ability, info)
    if info.fixedRange and info.fixedRange > 0 then
        return info.fixedRange
    end
    if info.fixedRangeKey then
        local value = SV(ability, info.fixedRangeKey)
        if value and value > 0 then
            return value
        end
    end
    return 0
end

--- Forward slash length (Kez Echo Slash katana_distance, etc.).
local function getSlashLength(ability, info)
    if info.slashLength and info.slashLength > 0 then
        return info.slashLength
    end
    if info.slashLengthKey then
        local value = SV(ability, info.slashLengthKey)
        if value and value > 0 then
            return value
        end
    end
    if info.lineLength and info.lineLength > 0 and info.beh == "no_target" then
        return info.lineLength
    end
    return 0
end

local function getAoeRadius(ability, info)
    if info.radius and info.radius > 0 then
        return info.radius
    end
    if info.radiusKey then
        local value = SV(ability, info.radiusKey)
        if value and value > 0 then
            return value
        end
    end
    local value = SVAny(ability, { "radius", "aoe", "area_of_effect", "width", "start_radius" })
    return value or 0
end

local function getCastRange(ability, info)
    local ok, value = TryCall(Ability.GetCastRange, ability)
    if ok and type(value) == "number" and value > 0 then
        return value
    end
    if info and info.castRange and info.castRange > 0 then
        return info.castRange
    end
    return 0
end

local function getCastPoint(ability)
    local ok, value = TryCall(Ability.GetCastPoint, ability, true)
    if ok and type(value) == "number" and value > 0 then
        return value
    end
    return 0.25
end

local function getImpactDelay(ability, info)
    if info.impactDelay and info.impactDelay > 0 then
        return info.impactDelay
    end
    if info.impactDelayKey then
        local value = SV(ability, info.impactDelayKey)
        if value and value > 0 then
            return value
        end
    end
    if info.delayedAoE then
        return SVAny(ability, { "delay", "impact_delay", "explode_delay", "light_strike_array_delay_time" }) or 0
    end
    return 0
end

local function getProjectileSpeed(ability, info)
    if info.projSpeed and info.projSpeed > 0 then
        -- Prefer live special value when the profile only baked a fallback.
        local live = SVAny(ability, {
            "dagger_speed", "projectile_speed", "proj_speed", "missile_speed",
            "shock_speed", "wave_speed", "orb_speed", "bolt_speed",
            "arrow_speed", "travel_speed", "spear_speed", "shard_speed",
        })
        if live and live > 0 then
            return live
        end
        return info.projSpeed
    end
    return SVAny(ability, {
        "dagger_speed", "projectile_speed", "proj_speed", "missile_speed",
        "shock_speed", "wave_speed", "orb_speed", "bolt_speed",
        "arrow_speed", "travel_speed", "spear_speed", "shard_speed",
    }) or 0
end

local function enrichAbility(ability, abilityName, profile)
    local info = mergeInfo(profile, { name = abilityName })
    info.beh = resolveBehaviorKind(ability, info)
    local fixed = getFixedRange(ability, info)
    if fixed > 0 then
        info.fixedRange = fixed
        if info.needFace == nil then
            info.needFace = true
        end
    end
    if not info.radius or info.radius <= 0 then
        info.radius = getAoeRadius(ability, info)
    end
    if not info.projSpeed or info.projSpeed <= 0 then
        info.projSpeed = getProjectileSpeed(ability, info)
    end
    info.impactDelay = getImpactDelay(ability, info)
    if info.impactDelay > 0 then
        info.delayedAoE = true
    end
    if not info.dmgKey and not info.attackPctKey and not info.critPctKey and not info.flatDamageKey then
        local _, key = SVAny(ability, {
            "damage", "base_damage", "AbilityDamage", "main_damage", "impact_damage",
            "blast_damage", "bolt_damage", "arc_damage", "beam_damage", "target_damage",
        })
        if key then
            info.dmgKey = key
        end
    end
    return info
end

--------------------------------------------------------------------------------
-- DAMAGE
--------------------------------------------------------------------------------

local FALLBACK_DMG_KEYS = {
    "damage", "base_damage", "damage_min", "AbilityDamage",
    "tooltip_damage", "main_damage", "impact_damage", "blast_damage",
    "bolt_damage", "wave_damage", "nova_damage", "arc_damage",
    "beam_damage", "bonus_damage", "target_damage",
}

local function getSpellAmp(hero)
    local ok, value = TryCall(NPC.GetBaseSpellAmp, hero)
    if ok and type(value) == "number" and value ~= 0 then
        if value > 1 then
            value = value / 100
        end
        return value
    end
    return 0
end

local function getAttackDamage(hero)
    -- Average of true min/max ≈ expected attack roll used by %attack spells.
    local okMin, dMin = TryCall(NPC.GetTrueDamage, hero)
    local okMax, dMax = TryCall(NPC.GetTrueMaximumDamage, hero)
    if okMin and type(dMin) == "number" and dMin > 0 then
        if okMax and type(dMax) == "number" and dMax >= dMin then
            return (dMin + dMax) * 0.5
        end
        return dMin
    end
    local minOk, minDmg = TryCall(NPC.GetMinDamage, hero)
    local bonusOk, bonusDmg = TryCall(NPC.GetBonusDamage, hero)
    local total = 0
    if minOk and type(minDmg) == "number" then
        total = total + minDmg
    end
    if bonusOk and type(bonusDmg) == "number" then
        total = total + bonusDmg
    end
    return math.max(0, total)
end

local function getAttackScaledDamage(hero, ability, info)
    local attackDamage = getAttackDamage(hero)
    if attackDamage <= 0 and not info.flatDamageKey and not info.flatDamage then
        return 0
    end
    local dmg = 0
    if info.attackPctKey then
        local pct = SV(ability, info.attackPctKey) or 0
        dmg = dmg + attackDamage * (pct / 100)
    end
    if info.critPctKey then
        local pct = SV(ability, info.critPctKey) or 0
        dmg = dmg + attackDamage * (pct / 100)
    end
    if info.flatDamageKey then
        dmg = dmg + (SV(ability, info.flatDamageKey) or 0)
    end
    if info.flatDamage then
        dmg = dmg + info.flatDamage
    end
    return math.max(0, dmg)
end

local function getAbilityDamage(hero, ability, info)
    local dmg = 0
    local hasAttackScale = info.attackPctKey or info.critPctKey or info.flatDamageKey or info.flatDamage

    if hasAttackScale then
        -- Profile owns the attack-scaled formula (PA dagger, MK strike, Mars rebuke, …).
        -- Do NOT also add Ability.GetDamage / dmgKey when it duplicates flatDamageKey.
        dmg = getAttackScaledDamage(hero, ability, info)
        if info.dmgKey and info.dmgKey ~= info.flatDamageKey then
            dmg = dmg + (SV(ability, info.dmgKey) or 0)
        end
    else
        local ok, value = TryCall(Ability.GetDamage, ability)
        if ok and type(value) == "number" and value > 0 then
            dmg = value
        end
        if dmg <= 0 and info.dmgKey then
            dmg = SV(ability, info.dmgKey) or 0
        end
        if dmg <= 0 then
            dmg = SVAny(ability, FALLBACK_DMG_KEYS) or 0
        end
    end

    if dmg <= 0 then
        return 0
    end
    if not info.noSpellAmp then
        dmg = dmg * (1 + getSpellAmp(hero))
    end
    return dmg
end

local function applyResistance(dmg, ability, info, target)
    local damageType = info.dmgTypeOverride
    if not damageType then
        local ok, dt = TryCall(Ability.GetDamageType, ability)
        if ok and dt == Enum.DamageTypes.DAMAGE_TYPE_PHYSICAL then
            damageType = "physical"
        elseif ok and dt == Enum.DamageTypes.DAMAGE_TYPE_PURE then
            damageType = "pure"
        else
            damageType = "magical"
        end
    end
    if damageType == "magical" then
        local ok, mult = TryCall(NPC.GetMagicalArmorDamageMultiplier, target)
        return dmg * ((ok and mult) or 1)
    end
    if damageType == "physical" then
        local ok, mult = TryCall(NPC.GetArmorDamageMultiplier, target)
        return dmg * ((ok and mult) or 1)
    end
    return dmg
end

local function getSelfDamage(ability, info)
    local selfDamage = 0
    if info.selfDamageKeys then
        for _, key in ipairs(info.selfDamageKeys) do
            local value = SV(ability, key)
            if type(value) == "number" and value > selfDamage then
                selfDamage = value
            end
        end
    end
    if info.selfDamageFlat and info.selfDamageFlat > selfDamage then
        selfDamage = info.selfDamageFlat
    end
    return selfDamage
end

local function canAffordSelfDamage(hero, ability, info)
    local selfDamage = getSelfDamage(ability, info)
    if selfDamage <= 0 then
        return true
    end
    local hp = Entity.GetHealth(hero) or 0
    local buffer = info.selfHpBuffer or 1
    return hp > selfDamage + buffer
end

local function getHitDelay(hero, ability, creep, info)
    local delay = getCastPoint(ability) + (info.impactDelay or 0)
    local speed = getProjectileSpeed(ability, info)
    if speed > 0 and creep then
        local dist = (Entity.GetAbsOrigin(hero) - Entity.GetAbsOrigin(creep)):Length2D()
        delay = delay + dist / speed
    elseif info.lineProjectile and creep then
        local dist = (Entity.GetAbsOrigin(hero) - Entity.GetAbsOrigin(creep)):Length2D()
        delay = delay + dist / 900
    end
    return delay
end

local function getSafetyBuffer(ability, info, hitDelay)
    local buffer = SAFETY_BUFFER_FLAT + getCastPoint(ability) * SAFETY_BUFFER_PER_CASTPOINT
    if info.delayedAoE then
        buffer = buffer + 8
    end

    local speed = getProjectileSpeed(ability, info)
    local isProjectile = (speed and speed > 0) or info.lineProjectile
    if isProjectile then
        -- Travel time: creep HP falls while the missile flies. Inflating buffer here
        -- forces a late cast and allies steal the CS. Keep a small variance pad only.
        buffer = math.max(SAFETY_BUFFER_FLAT, buffer * 0.65)
    elseif hitDelay and hitDelay > 0.35 then
        buffer = buffer + (hitDelay - 0.35) * 15
    end
    return buffer
end

local function canSecureKill(effectiveDmg, creepHP, buffer)
    return effectiveDmg >= (creepHP + buffer)
end

--------------------------------------------------------------------------------
-- RESOLVE POOL
--------------------------------------------------------------------------------

local function resolveProfileAbility(hero, ability, abilityName)
    if isAbilityExcluded(ability, true) then
        return nil
    end
    local profile = LASTHIT_PROFILES and LASTHIT_PROFILES[abilityName]
    if not profile then
        return nil
    end
    local info = enrichAbility(ability, abilityName, profile)
    if not info.beh then
        return nil
    end
    return info
end

local function resolveFallbackAbility(hero, ability, abilityName)
    if isAbilityExcluded(ability, false) then
        return nil
    end
    local info = enrichAbility(ability, abilityName, {
        name = abilityName,
        autoDetected = true,
    })
    if not info.beh then
        return nil
    end
    if getAbilityDamage(hero, ability, info) <= 0 then
        return nil
    end
    return info
end

local function getHeroAbilityPrefix(heroName)
    return string.match(heroName or "", "^npc_dota_hero_(.+)$")
end

local function getResolvedHeroAbilityInfos(hero)
    local heroName = NPC.GetUnitName(hero)
    if not heroName or heroName == "" then
        return {}, nil
    end

    local signature = buildHeroAbilitySignature(hero)
    local cached = resolvedAbilityInfoCache[signature]
    if cached then
        return cached.abilities, signature
    end

    local resolved = {}
    local seen = {}

    local function tryAdd(ability, abilityName)
        if not ability or not abilityName or seen[abilityName] then
            return
        end
        local info = resolveProfileAbility(hero, ability, abilityName)
        if not info then
            info = resolveFallbackAbility(hero, ability, abilityName)
        end
        if info then
            resolved[#resolved + 1] = info
            seen[abilityName] = true
        end
    end

    for _, ability in ipairs(enumerateHeroAbilities(hero)) do
        tryAdd(ability, getAbilityName(ability))
    end

    local prefix = getHeroAbilityPrefix(heroName)
    if prefix and LASTHIT_PROFILES then
        local token = prefix .. "_"
        for abilityName, _ in pairs(LASTHIT_PROFILES) do
            if not seen[abilityName] and string.sub(abilityName, 1, #token) == token then
                tryAdd(getAbilityByName(hero, abilityName), abilityName)
            end
        end
    end

    resolvedAbilityInfoCache[signature] = { abilities = resolved }
    return resolved, signature
end

--------------------------------------------------------------------------------
-- RANGE / CAST
--------------------------------------------------------------------------------

local function getAttackRange(hero)
    local ok, value = TryCall(NPC.GetAttackRange, hero)
    if ok and type(value) == "number" then
        return value
    end
    return 150
end

local function isCreepInAttackRange(hero, creep)
    local dist = (Entity.GetAbsOrigin(hero) - Entity.GetAbsOrigin(creep)):Length2D()
    local heroHull = NPC.GetHullRadius(hero) or 0
    local creepHull = NPC.GetHullRadius(creep) or 0
    return dist <= getAttackRange(hero) + heroHull + creepHull + AUTO_ATTACK_RANGE_EPSILON
end

local function isCreepInAbilityRange(hero, ability, creep, info)
    local heroPos = Entity.GetAbsOrigin(hero)
    local creepPos = Entity.GetAbsOrigin(creep)
    local dist = (heroPos - creepPos):Length2D()

    local fixed = getFixedRange(ability, info)
    if fixed > 0 then
        local r = getAoeRadius(ability, info)
        if r <= 0 then r = 250 end
        return math.abs(dist - fixed) <= r
    end

    -- Forward slash (Echo Slash): length along facing + width. We face before cast.
    local slashLen = getSlashLength(ability, info)
    if slashLen > 0 then
        local width = info.lineRadius or getAoeRadius(ability, info)
        if width <= 0 then width = 150 end
        return dist <= slashLen + width
    end

    if info.beh == "no_target" then
        local r = getAoeRadius(ability, info)
        if r <= 0 then r = 350 end
        return dist <= r
    end
    local castRange = getCastRange(ability, info)
    if castRange <= 0 then castRange = 600 end
    local heroHull = NPC.GetHullRadius(hero) or 0
    local creepHull = NPC.GetHullRadius(creep) or 0
    return dist <= castRange + heroHull + creepHull
end

local function getAbilitySearchRadius(ability, info)
    local pad = 64
    local fixed = getFixedRange(ability, info)
    local aoe = getAoeRadius(ability, info)
    if fixed > 0 then
        if aoe <= 0 then aoe = 250 end
        return fixed + aoe + pad
    end

    local slashLen = getSlashLength(ability, info)
    if slashLen > 0 then
        local width = info.lineRadius or aoe
        if width <= 0 then width = 150 end
        return slashLen + width + pad
    end

    if info.beh == "no_target" then
        if aoe <= 0 then aoe = 350 end
        return aoe + pad
    end
    local castRange = getCastRange(ability, info)
    if castRange <= 0 then castRange = 600 end
    if info.lineProjectile then
        return math.max(castRange, info.lineLength or castRange) + pad
    end
    return castRange + pad
end

local function isAbilitySelected(info)
    if not UI.Abilities then
        return true
    end
    local ok, selected = TryCall(function() return UI.Abilities:Get(info.name) end)
    if ok and selected == false then
        return false
    end
    return true
end

local function getHeroSpellSearchRange(hero, abilityInfos)
    local maxRange = 0
    for _, info in ipairs(abilityInfos) do
        if isAbilitySelected(info) then
            local ability = getAbilityByName(hero, info.name)
            if ability and (Ability.GetLevel(ability) or 0) > 0 then
                local range = getAbilitySearchRadius(ability, info)
                if range > maxRange then
                    maxRange = range
                end
            end
        end
    end
    return maxRange
end

local function faceCreep(hero, creepPos)
    local player = Players.GetLocal()
    if not player then
        return
    end
    Player.PrepareUnitOrders(
        player,
        Enum.UnitOrder.DOTA_UNIT_ORDER_MOVE_TO_DIRECTION,
        nil,
        creepPos,
        nil,
        Enum.PlayerOrderIssuer.DOTA_ORDER_ISSUER_HERO_ONLY,
        hero,
        false, false, false, false,
        ORDER_ID
    )
end

local function shouldFace(info)
    if info.needFace or info.fixedRange or info.fixedRangeKey then
        return true
    end
    return info.beh == "point" or info.beh == "no_target"
end

local function castOnCreep(hero, ability, creep, info)
    local creepPos = Entity.GetAbsOrigin(creep)
    if shouldFace(info) then
        faceCreep(hero, creepPos)
    end
    if info.beh == "target" then
        Ability.CastTarget(ability, creep, false, false, false, ORDER_ID)
    elseif info.beh == "point" then
        Ability.CastPosition(ability, creepPos, false, false, false, ORDER_ID)
    elseif info.beh == "no_target" then
        Ability.CastNoTarget(ability, false, false, false, ORDER_ID)
    end
end

--------------------------------------------------------------------------------
-- CREEPS / FILTERS
--------------------------------------------------------------------------------

local function getMultiComboValue(widget, item)
    if not widget or not item then
        return nil
    end
    local ok, value = TryCall(function() return widget:Get(item) end)
    if ok then
        return value
    end
    return nil
end

local function isConditionEnabled(item, default)
    local value = getMultiComboValue(UI.Conditions, conditionLabel(item))
    if value ~= nil then
        return value
    end
    return default
end

local function isCreepFilterEnabled(item, default)
    local value = getMultiComboValue(UI.CreepTypes, creepFilterLabel(item))
    if value ~= nil then
        return value
    end
    return default
end

local function isCreepValid(creep)
    if not creep or not Entity.IsAlive(creep) or NPC.IsHero(creep) then
        return false
    end
    -- Never last-hit bosses: Tormentor (npc_dota_miniboss), Roshan, other TYPE_BOSS.
    if NPC.IsTormentor(creep) or NPC.IsRoshan(creep) or NPC.IsBoss(creep) then
        return false
    end
    local unitName = NPC.GetUnitName(creep) or ""
    if unitName == "npc_dota_miniboss"
        or unitName:find("roshan", 1, true)
        or unitName:find("miniboss", 1, true) then
        return false
    end
    if unitName:find("siege") then
        return isCreepFilterEnabled(CREEP_FILTER_ITEMS.siege, false)
    end
    if NPC.IsNeutral(creep) then
        return isCreepFilterEnabled(CREEP_FILTER_ITEMS.neutral, false)
    end
    if NPC.IsRanged(creep) then
        return isCreepFilterEnabled(CREEP_FILTER_ITEMS.ranged, true)
    end
    if NPC.IsCreep(creep) or NPC.IsLaneCreep(creep) then
        return isCreepFilterEnabled(CREEP_FILTER_ITEMS.melee, true)
    end
    return false
end

local function creepPriority(creep, hp)
    local score = math.max(0, 120 - hp)
    if NPC.IsRanged(creep) then
        score = score + 25
    end
    local unitName = NPC.GetUnitName(creep) or ""
    if unitName:find("siege") then
        score = score + 8
    end
    return score
end

local function isHeroBusyAttacking(hero)
    return NPC.IsAttacking(hero) and true or false
end

local function canAutoAttackKill(hero, creep)
    if not isCreepInAttackRange(hero, creep) then
        return false
    end
    local hp = Entity.GetHealth(creep) or 0
    local dmg = getAttackDamage(hero)
    local ok, mult = TryCall(NPC.GetArmorDamageMultiplier, creep)
    if ok and type(mult) == "number" then
        dmg = dmg * mult
    end
    return dmg >= hp
end

--------------------------------------------------------------------------------
-- MENU
--------------------------------------------------------------------------------

local function getSpellIcon(abilityName)
    return "panorama/images/spellicons/" .. abilityName .. "_png.vtex_c"
end

local function styleMenuWidget(widget, text, tooltip, icon)
    if not widget then
        return widget
    end
    if text and widget.ForceLocalization then
        widget:ForceLocalization(text)
    end
    if icon and widget.Icon then
        widget:Icon(icon)
    end
    if tooltip and widget.ToolTip then
        widget:ToolTip(tooltip)
    end
    return widget
end

local unpackArgs = table.unpack
local cachedHoldBind = nil
local cachedHoldBindLabel = nil
local GLOBAL_BIND_WIDGET_CANDIDATES = {
    { label = "lhh-key", args = { "Creeps", "Main", "[v2]Last Hit Helper", "Main", "Global Settings", "Key" } },
    { label = "lhh-hotkey", args = { "Creeps", "Main", "[v2]Last Hit Helper", "Main", "Global Settings", "Hotkey" } },
    { label = "lhh-additional-hotkey", args = { "Creeps", "Main", "[v2]Last Hit Helper", "Main", "Global Settings", "Additional Settings", "Hotkey" } },
}

local function isValidBindWidget(widget)
    if not widget then
        return false
    end
    -- CMenuBind: IsDown / IsPressed / Get (no GetKey in stubs).
    if widget.IsDown or widget.IsPressed then
        return true
    end
    if widget.Type and Enum and Enum.WidgetType then
        local ok, widgetType = TryCall(function() return widget:Type() end)
        if ok and widgetType ~= nil then
            for name, enumValue in pairs(Enum.WidgetType) do
                if enumValue == widgetType and string.find(string.lower(tostring(name)), "bind", 1, true) then
                    return true
                end
            end
        end
    end
    return false
end

local function findMenuWidgetByCandidates(candidates, validator)
    if not Menu or not Menu.Find then
        return nil, nil
    end
    for _, candidate in ipairs(candidates) do
        local ok, widget = TryCall(Menu.Find, unpackArgs(candidate.args))
        if ok and validator(widget) then
            return widget, candidate.label
        end
    end
    return nil, nil
end

local function getGlobalHoldBindWidget()
    if cachedHoldBind and isValidBindWidget(cachedHoldBind) then
        return cachedHoldBind, cachedHoldBindLabel
    end

    local widget, label = findMenuWidgetByCandidates(GLOBAL_BIND_WIDGET_CANDIDATES, isValidBindWidget)
    cachedHoldBind = widget
    cachedHoldBindLabel = label
    return widget, label
end

--- Hold-key for Last Hit Helper global Key bind (CMenuBind.IsDown).
local function isMenuBindPressed(widget)
    if not widget then
        return false
    end

    if widget.IsDown then
        local ok, isDown = TryCall(function() return widget:IsDown() end)
        if ok and type(isDown) == "boolean" then
            return isDown
        end
    end

    if widget.IsPressed then
        local ok, isPressed = TryCall(function() return widget:IsPressed() end)
        if ok and type(isPressed) == "boolean" then
            return isPressed
        end
    end

    -- Some binds expose hold state via Get() boolean.
    if widget.Get then
        local ok, value = TryCall(function() return widget:Get() end)
        if ok and type(value) == "boolean" then
            return value
        end
    end

    return false
end

local function refreshAbilitiesWidgetState()
    if not UI.Abilities then
        return
    end
    styleMenuWidget(UI.Abilities, t("abilities"), t("abilities_tip"), Icons.abilities)
end

local function abilityPrefKey(abilityName)
    return ABILITY_PREF_PREFIX .. tostring(abilityName)
end

--- Cached / Config preference. nil = never chosen → default ON.
local function loadAbilityPref(abilityName)
    if not abilityName or abilityName == "none" then
        return nil
    end
    if abilitiesPrefs[abilityName] ~= nil then
        return abilitiesPrefs[abilityName]
    end
    local ok, stored = TryCall(function()
        return Config.ReadInt(CONFIG_SECTION, abilityPrefKey(abilityName), -1)
    end)
    if ok and type(stored) == "number" and stored >= 0 then
        abilitiesPrefs[abilityName] = stored == 1
        return abilitiesPrefs[abilityName]
    end
    return nil
end

local function saveAbilityPref(abilityName, enabled)
    if not abilityName or abilityName == "none" then
        return
    end
    local on = enabled == true
    abilitiesPrefs[abilityName] = on
    TryCall(function()
        Config.WriteInt(CONFIG_SECTION, abilityPrefKey(abilityName), on and 1 or 0)
    end)
end

local function isAbilityPrefEnabled(abilityName)
    local pref = loadAbilityPref(abilityName)
    if pref ~= nil then
        return pref
    end
    return true
end

local function syncAbilitiesPrefsFromWidget()
    if not UI.Abilities or not UI.Abilities.Get then
        return
    end
    local listed = nil
    if UI.Abilities.List then
        local okList, value = TryCall(function() return UI.Abilities:List() end)
        if okList and type(value) == "table" then
            listed = value
        end
    end
    if not listed then
        return
    end
    for _, itemId in ipairs(listed) do
        if itemId and itemId ~= "none" then
            local okGet, enabled = TryCall(function() return UI.Abilities:Get(itemId) end)
            if okGet and type(enabled) == "boolean" then
                saveAbilityPref(itemId, enabled)
            end
        end
    end
end

local function applyAbilitiesPrefsToWidget()
    if not UI.Abilities or not UI.Abilities.Set or not UI.Abilities.List then
        return
    end
    local okList, listed = TryCall(function() return UI.Abilities:List() end)
    if not okList or type(listed) ~= "table" then
        return
    end
    for _, itemId in ipairs(listed) do
        if itemId and itemId ~= "none" then
            local enabled = isAbilityPrefEnabled(itemId)
            TryCall(function()
                UI.Abilities:Set(itemId, enabled)
            end)
        end
    end
end

local function bindAbilitiesPrefCallback()
    if abilitiesCallbackBound or not UI.Abilities or not UI.Abilities.SetCallback then
        return
    end
    UI.Abilities:SetCallback(function()
        syncAbilitiesPrefsFromWidget()
    end, false)
    abilitiesCallbackBound = true
end

local function buildAbilitiesSelector(heroName, abilities, signature)
    if not menuGroup or not abilities then
        return
    end

    -- Keep live toggles before list rebuild (hero change / new skill level).
    if abilitiesUiReady then
        syncAbilitiesPrefsFromWidget()
    end

    local items = {}
    local seen = {}
    for _, info in ipairs(abilities) do
        if info.name and not seen[info.name] then
            seen[info.name] = true
            -- Default ON; honor Config / previous user choice.
            local enabled = isAbilityPrefEnabled(info.name)
            items[#items + 1] = {
                info.name,
                getSpellIcon(info.name),
                enabled,
            }
        end
    end

    if #items == 0 then
        items[1] = { "none", getSpellIcon("invoker_empty1"), false }
    end

    if UI.Abilities and UI.Abilities.Update then
        -- saveToConfig=false: do not let Update overwrite user prefs with rebuild.
        -- Persistence is Config.WriteInt via callback / apply below.
        UI.Abilities:Update(items, true, false)
    else
        UI.Abilities = menuGroup:MultiSelect(t("abilities"), items, true)
        abilitiesCallbackBound = false
    end

    applyAbilitiesPrefsToWidget()
    bindAbilitiesPrefCallback()
    refreshAbilitiesWidgetState()
    abilitiesUiReady = true
    currentHeroName = heroName
    currentHeroAbilitySignature = signature
end

--- Always keep Abilities list in sync with local hero (bind not required).
local function syncAbilitiesUi(hero)
    if not hero or not menuGroup then
        return
    end
    local heroName = NPC.GetUnitName(hero)
    local abilities, signature = getResolvedHeroAbilityInfos(hero)
    if heroName ~= currentHeroName or signature ~= currentHeroAbilitySignature then
        buildAbilitiesSelector(heroName, abilities or {}, signature)
    end
end

Script.OnScriptsLoaded = function()
    MENU_LANG = detectMenuLanguage()
    cachedHoldBind = nil
    cachedHoldBindLabel = nil
    abilitiesUiReady = false
    abilitiesCallbackBound = false
    abilitiesPrefs = {} -- re-read from Config as abilities appear

    local group = Menu.Create(
        "Creeps", "Main", "[v2]Last Hit Helper", "Main", "Skill LastHit"
    )
    menuGroup = group

    UI.Enable = group:Switch(t("enable"), false, Icons.enable)
    styleMenuWidget(UI.Enable, t("enable"), t("enable_tip"), nil)

    -- Abilities always visible under the script group (not gated by Enable/bind).
    UI.Abilities = group:MultiSelect(t("abilities"), {
        { "none", getSpellIcon("invoker_empty1"), false },
    }, true)
    bindAbilitiesPrefCallback()
    refreshAbilitiesWidgetState()

    local gear = UI.Enable:Gear(t("settings"))
    UI.SettingsGear = gear

    UI.Conditions = gear:MultiCombo(t("conditions"), {
        conditionLabel(CONDITION_ITEMS.smart),
    }, {
        conditionLabel(CONDITION_ITEMS.smart),
    })

    UI.CreepTypes = gear:MultiCombo(t("creeps"), {
        creepFilterLabel(CREEP_FILTER_ITEMS.melee),
        creepFilterLabel(CREEP_FILTER_ITEMS.ranged),
        creepFilterLabel(CREEP_FILTER_ITEMS.neutral),
        creepFilterLabel(CREEP_FILTER_ITEMS.siege),
    }, {
        creepFilterLabel(CREEP_FILTER_ITEMS.melee),
        creepFilterLabel(CREEP_FILTER_ITEMS.ranged),
    })

    UI.MinMana = gear:Slider(t("min_mana"), 0, 80, 15, "%d%%")
    UI.Debug = gear:Switch(t("debug"), false, Icons.debug)

    styleMenuWidget(UI.Conditions, t("conditions"), t("conditions_tip"), Icons.conditions)
    styleMenuWidget(UI.CreepTypes, t("creeps"), t("creeps_tip"), Icons.creeps)
    styleMenuWidget(UI.MinMana, t("min_mana"), t("min_mana_tip"), Icons.mana)

    UI.Enable:SetCallback(function()
        local on = UI.Enable:Get()
        UI.Conditions:Disabled(not on)
        UI.CreepTypes:Disabled(not on)
        UI.MinMana:Disabled(not on)
        UI.Debug:Disabled(not on)
        -- Abilities stay interactive always.
    end, true)

    local bind, bindLabel = getGlobalHoldBindWidget()
    if bind then
        Log.Write(DEBUG_PREFIX .. "Hold bind linked: " .. tostring(bindLabel)
            .. " (Creeps → [v2]Last Hit Helper → Global Settings → Key)")
    else
        Log.Write(DEBUG_PREFIX .. "Hold bind NOT found. Expected Menu.Find("
            .. "\"Creeps\", \"Main\", \"[v2]Last Hit Helper\", \"Main\", \"Global Settings\", \"Key\")")
    end
    Log.Write(DEBUG_PREFIX .. "Skill LastHit slim menu ready")
end

--------------------------------------------------------------------------------
-- MAIN
--------------------------------------------------------------------------------

Script.OnUpdate = function()
    local myHero = Heroes.GetLocal()
    if myHero and Entity.IsAlive(myHero) then
        syncAbilitiesUi(myHero)
    end

    if not UI.Enable or not UI.Enable:Get() then
        return
    end

    local holdBind, bindLabel = getGlobalHoldBindWidget()
    if not holdBind then
        return
    end
    if not isMenuBindPressed(holdBind) then
        return
    end
    if not myHero or not Entity.IsAlive(myHero) then
        return
    end
    if NPC.IsSilenced(myHero) or NPC.IsStunned(myHero) then
        return
    end
    if NPC.IsChannellingAbility(myHero) then
        return
    end

    local smart = isConditionEnabled(CONDITION_ITEMS.smart, true)
    if smart and isHeroBusyAttacking(myHero) then
        local aaRange = getAttackRange(myHero) + (NPC.GetHullRadius(myHero) or 0) + AUTO_ATTACK_RANGE_EPSILON + 40
        local near = NPCs.InRadius(
            Entity.GetAbsOrigin(myHero),
            aaRange,
            Entity.GetTeamNum(myHero),
            Enum.TeamType.TEAM_ENEMY
        )
        if near then
            for _, creep in ipairs(near) do
                if isCreepValid(creep) and canAutoAttackKill(myHero, creep) then
                    dbgThrottle("Respect AA kill")
                    return
                end
            end
        end
    end

    local mana = NPC.GetMana(myHero) or 0
    local maxMana = NPC.GetMaxMana(myHero) or 1
    local manaPercent = (maxMana > 0) and (mana / maxMana * 100) or 0
    if manaPercent < (UI.MinMana and UI.MinMana:Get() or 15) then
        return
    end

    local now = GameRules.GetGameTime()
    local castLock = lastCastLockDuration > 0 and lastCastLockDuration or CAST_INTERVAL
    if now - lastCastTime < castLock then
        return
    end
    if lastTargetEntity and (now - lastTargetTime) < lastTargetLockDuration then
        -- soft lock only applied per-candidate below
    end

    local heroName = NPC.GetUnitName(myHero)
    local heroAbilities = getResolvedHeroAbilityInfos(myHero)
    if not heroAbilities or #heroAbilities == 0 then
        dbgThrottleKey("pool:" .. tostring(heroName), "No ability pool: " .. tostring(heroName), 2.0)
        return
    end

    local searchRange = getHeroSpellSearchRange(myHero, heroAbilities)
    if searchRange <= 0 then
        return
    end

    local creeps = NPCs.InRadius(
        Entity.GetAbsOrigin(myHero),
        searchRange,
        Entity.GetTeamNum(myHero),
        Enum.TeamType.TEAM_ENEMY
    )
    if not creeps or #creeps == 0 then
        return
    end

    local bestCreep, bestAbility, bestInfo, bestScore = nil, nil, nil, -1

    for _, info in ipairs(heroAbilities) do
        if not isAbilitySelected(info) then
            goto continue_ability
        end

        local ability = getAbilityByName(myHero, info.name)
        if not ability or (Ability.GetLevel(ability) or 0) <= 0 then
            goto continue_ability
        end
        if not Ability.IsCastable(ability, mana) then
            goto continue_ability
        end
        if (Ability.GetCooldown(ability) or 0) > 0 then
            goto continue_ability
        end
        if Ability.IsInAbilityPhase(ability) then
            goto continue_ability
        end
        if not canAffordSelfDamage(myHero, ability, info) then
            goto continue_ability
        end

        local baseDmg = getAbilityDamage(myHero, ability, info)
        if baseDmg <= 0 then
            goto continue_ability
        end

        for _, creep in ipairs(creeps) do
            if not isCreepValid(creep) then
                goto continue_creep
            end
            if isCreepInAttackRange(myHero, creep) then
                goto continue_creep
            end
            if lastTargetEntity == creep and (now - lastTargetTime) < lastTargetLockDuration then
                goto continue_creep
            end
            if not isCreepInAbilityRange(myHero, ability, creep, info) then
                goto continue_creep
            end

            local hp = Entity.GetHealth(creep) or 0
            local hitDelay = getHitDelay(myHero, ability, creep, info)
            local effective = applyResistance(baseDmg, ability, info, creep)
            local buffer = getSafetyBuffer(ability, info, hitDelay)
            if not canSecureKill(effective, hp, buffer) then
                goto continue_creep
            end

            local score = creepPriority(creep, hp) + math.min(40, effective - hp)
            if info.autoDetected then
                score = score - 2
            end
            if score > bestScore then
                bestScore = score
                bestCreep = creep
                bestAbility = ability
                bestInfo = info
            end

            ::continue_creep::
        end

        ::continue_ability::
    end

    if not bestCreep or not bestAbility or not bestInfo then
        return
    end

    -- Revalidate once before cast.
    if isCreepInAttackRange(myHero, bestCreep) or not Entity.IsAlive(bestCreep) then
        return
    end
    local hp = Entity.GetHealth(bestCreep) or 0
    local baseDmg = getAbilityDamage(myHero, bestAbility, bestInfo)
    local effective = applyResistance(baseDmg, bestAbility, bestInfo, bestCreep)
    local hitDelay = getHitDelay(myHero, bestAbility, bestCreep, bestInfo)
    local buffer = getSafetyBuffer(bestAbility, bestInfo, hitDelay)
    if not canSecureKill(effective, hp, buffer) then
        return
    end
    if not isCreepInAbilityRange(myHero, bestAbility, bestCreep, bestInfo) then
        return
    end

    dbg(string.format(
        "CAST %s → %s (hp=%d dmg=%.0f buf=%.0f score=%.0f)",
        bestInfo.name,
        NPC.GetUnitName(bestCreep) or "?",
        hp,
        effective,
        buffer,
        bestScore
    ))

    castOnCreep(myHero, bestAbility, bestCreep, bestInfo)
    lastCastTime = now
    lastCastLockDuration = math.max(CAST_INTERVAL, getCastPoint(bestAbility) + 0.10)
    lastTargetEntity = bestCreep
    lastTargetTime = now
    lastTargetLockDuration = math.min(1.0, math.max(0.15, hitDelay * 0.85))
end

Script.OnGameEnd = function()
    lastCastTime = 0
    lastCastLockDuration = 0
    lastDebugTime = 0
    lastDebugByKey = {}
    lastTargetEntity = nil
    lastTargetTime = 0
    lastTargetLockDuration = 0
    currentHeroName = nil
    currentHeroAbilitySignature = nil
    resolvedAbilityInfoCache = {}
    cachedHoldBind = nil
    cachedHoldBindLabel = nil
    abilitiesUiReady = false
    -- Keep abilitiesPrefs / Config across games; only UI list rebuilds next match.
end

return Script
